CREATE VIEW VW_EMP_PLATEMENT AS
SELECT z.SYAIN_NO AS EMP_CODE,b.SIMEI AS EMP_NAME,
z.KENMU_KBN AS ROLE, z.SOSIKI_CODE AS ORG_CODE,
k.SOSIKI_NAME AS ORG_NAME,v.POSITION_X AS Hierarchy,
t.SOSIKI_CODE_1 AS Hierarchy1,
t.SOSIKI_CODE_2 AS Hierarchy2,
(SELECT SOSIKI_NAME FROM TM_SOSIKI WHERE SOSIKI_CODE=t.SOSIKI_CODE_2) AS Hierarchy2_Name,
t.SOSIKI_CODE_3 AS Hierarchy3,
(SELECT SOSIKI_NAME FROM TM_SOSIKI WHERE SOSIKI_CODE=t.SOSIKI_CODE_3) AS Hierarchy3_Name,
t.SOSIKI_CODE_4 AS Hierarch4 ,
(SELECT SOSIKI_NAME FROM TM_SOSIKI WHERE SOSIKI_CODE=t.SOSIKI_CODE_4) AS Hierarchy4_Name
FROM TM_SYOZOKU z 
LEFT JOIN TM_SOSIKI k
ON z.SOSIKI_CODE=k.SOSIKI_CODE
LEFT JOIN TM_TAIKEI t
ON k.HYOZI_NO=t.KAISO_JUNI_NO
LEFT JOIN TM_TAIKEI_VERTICAL v
ON k.SOSIKI_CODE=v.SOSIKI_CODE
LEFT JOIN TM_SYAIN_BASE b
ON z.SYAIN_NO=b.SYAIN_NO