SELECT SUP.*,CUR.CHR1 AS CURRENCY,VAT.NUM1 AS VAT_VALUE
FROM TM_HANYO SUP
LEFT JOIN TM_HANYO CUR
ON SUP.CHR2=CUR.HANYO_CODE
LEFT JOIN TM_HANYO VAT
ON SUP.CHR5=VAT.HANYO_CODE
WHERE SUP.HANYO_KBN='SAP2-Supplier'
AND CUR.HANYO_KBN='SAP3-Currency'
AND VAT.HANYO_KBN='SAP4-VAT'